local ItemLinkParser = require("src.ItemLinkParser")

describe("ItemLinkParser", function()
	it("returns parse error for invalid links", function()
		local parsed, err = ItemLinkParser.ParseItemLink("not-a-link")
		assert.is_nil(parsed)
		assert.is_true((err or ""):find("invalid item link", 1, true) ~= nil)
	end)

	it("parses item, enchant, and gem ids", function()
		local parsed, err = ItemLinkParser.ParseItemLink("item:28393:27977:24030:24030:24030:24030")
		assert.is_nil(err)
		parsed = assert(parsed)
		assert.are.equal(28393, parsed.itemId)
		assert.are.equal(27977, parsed.enchantId)
		assert.are.same({ 24030, 24030, 24030, 24030 }, parsed.gems)
	end)

	it("preserves empty item string fields instead of shifting values", function()
		local parsed, err = ItemLinkParser.ParseItemLink("item:28393::0:0:0:0")
		assert.is_nil(err)
		parsed = assert(parsed)
		assert.are.equal(28393, parsed.itemId)
		assert.are.equal(0, parsed.enchantId)
		assert.are.same({ 0, 0, 0, 0 }, parsed.gems)
	end)
end)
