name: Lua Unit Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

      - name: Check Lua formatting
        run: stylua --check src spec

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install Busted
        run: luarocks install busted

      - name: Execute Test Suite
        run: |
          eval "$(luarocks path)"
          busted spec
